repos:
-   repo: https://github.com/ambv/black
    rev: stable 
    hooks:
    - id: black
      language_version: python3.6
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v1.3.0
    hooks:
    -   id: flake8
        args:
        - '--config=.flake8'
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.610
    hooks:
    -   id: mypy
        args: ['--no-strict-optional', '--ignore-missing-imports']
